name: checks

on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.6.0

      - name: Build an image from Dockerfile
        run: |
          docker build -t dockerfile-best-practice-sandbox .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: dockerfile-best-practice-sandbox
          format: 'table'
          exit-code: '1'
